Class %ZPM.PackageManager.Developer.Annotation.Tag.API.Object.Instantiable Extends (%ZPM.PackageManager.Developer.Annotation.Tag.AnchorTag, %ZPM.PackageManager.Developer.Annotation.Tag.SupportsAvailability)
{

Parameter XMLNAME = "API_Object_Instantiable";

Storage Default
{
<Data name="InstantiableDefaultData">
<Subscript>"Instantiable"</Subscript>
<Value name="1">
<Value>Availability</Value>
</Value>
</Data>
<DefaultData>InstantiableDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
