Class %ZPM.PackageManager.Developer.Document.APIStream Extends %ZPM.PackageManager.Developer.Document.AbstractStream
{

Storage Default
{
<Data name="APIStreamDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Name</Value>
</Value>
<Value name="3">
<Value>Contents</Value>
</Value>
<Value name="4">
<Value>Hash</Value>
</Value>
<Value name="5">
<Value>LastModifiedTimestamp</Value>
</Value>
</Data>
<DataLocation>^%ZPM.Dev.APIDocD</DataLocation>
<DefaultData>APIStreamDefaultData</DefaultData>
<IdLocation>^%ZPM.Dev.APIDocD</IdLocation>
<IndexLocation>^%ZPM.Dev.APIDocI</IndexLocation>
<StreamLocation>^%ZPM.Dev.APIDocS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
