Class %ZPM.StudioDocument.ModuleStream Extends %ZPM.StudioDocument.AbstractStream
{

Storage Default
{
<Data name="ModuleStreamDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Name</Value>
</Value>
<Value name="3">
<Value>Contents</Value>
</Value>
<Value name="4">
<Value>Hash</Value>
</Value>
<Value name="5">
<Value>LastModifiedTimestamp</Value>
</Value>
</Data>
<DataLocation>^ZPM.StudioDoc.ModuleStreamD</DataLocation>
<DefaultData>ModuleStreamDefaultData</DefaultData>
<IdLocation>^ZPM.StudioDoc.ModuleStreamD</IdLocation>
<IndexLocation>^ZPM.StudioDoc.ModuleStreamI</IndexLocation>
<StreamLocation>^ZPM.StudioDoc.ModuleStreamS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
