Class %ZPM.PackageManager.Developer.Annotation.Tag.API.Query Extends (%ZPM.PackageManager.Developer.Annotation.Tag.AnchorTag, %ZPM.PackageManager.Developer.Annotation.Tag.SupportsAvailability)
{

Parameter XMLNAME = "API_Query";

Storage Default
{
<Data name="QueryDefaultData">
<Subscript>"Query"</Subscript>
<Value name="1">
<Value>Availability</Value>
</Value>
</Data>
<DefaultData>QueryDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
