Class %ZPM.PackageManager.Developer.Annotation.Tag.API.Extensible Extends (%ZPM.PackageManager.Developer.Annotation.Tag.AnchorTag, %ZPM.PackageManager.Developer.Annotation.Tag.SupportsAvailability)
{

Parameter XMLNAME = "API_Extensible";

Parameter AddIfOmitted = 1;

Storage Default
{
<Data name="ExtensibleDefaultData">
<Subscript>"Extensible"</Subscript>
<Value name="1">
<Value>Availability</Value>
</Value>
</Data>
<DefaultData>ExtensibleDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
