Class %ZPM.PackageManager.Developer.Annotation.Tag.API.Overrideable Extends (%ZPM.PackageManager.Developer.Annotation.Tag.AnchorTag, %ZPM.PackageManager.Developer.Annotation.Tag.SupportsAvailability)
{

Parameter XMLNAME = "API_Overrideable";

Parameter AddIfOmitted = 1;

Storage Default
{
<Data name="OverrideableDefaultData">
<Subscript>"Overrideable"</Subscript>
<Value name="1">
<Value>Availability</Value>
</Value>
</Data>
<DefaultData>OverrideableDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
