Class %ZPM.PackageManager.Developer.Annotation.Tag.API.Parameter Extends (%ZPM.PackageManager.Developer.Annotation.Tag.AnchorTag, %ZPM.PackageManager.Developer.Annotation.Tag.SupportsAvailability)
{

Parameter XMLNAME = "API_Parameter";

Storage Default
{
<Data name="ParameterDefaultData">
<Subscript>"Parameter"</Subscript>
<Value name="1">
<Value>Availability</Value>
</Value>
</Data>
<DefaultData>ParameterDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
