Class %ZPM.PackageManager.Developer.Annotation.Tag.API.Property Extends (%ZPM.PackageManager.Developer.Annotation.Tag.AnchorTag, %ZPM.PackageManager.Developer.Annotation.Tag.SupportsAvailability)
{

Parameter XMLNAME = "API_Property";

Storage Default
{
<Data name="PropertyDefaultData">
<Subscript>"Property"</Subscript>
<Value name="1">
<Value>Availability</Value>
</Value>
</Data>
<DefaultData>PropertyDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
